config/routes.rb
Web::Application.routes.draw do

  devise_for :users

  resources :apartments
  resources :houses
  resources :filters

  root :to => "filters#index"

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  attr_accessible :description, :loan, :locality, :name, :owner, :ownership, :prize, :type

  attr_accessible :property_id, :age, :area, :bathroom, :cellar, :escalator, :internet, :loft, :material, :mezonet,
                  :parking, :room, :state, :telephone, :toalette, :tv, :state_id


  belongs_to :user
  belongs_to :state
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

  def show
    @apartment = Apartment.find(params[:id])
  end

  def index
    @apartment = Apartment.all
  end

  def new
    @apartment = Apartment.new
  end

  def create
    @apartment = Apartment.new

    @apartment = Apartment.new(params[:apartment])
    @apartment.user_id = current_user.id
    respond_to do |format|
      if @apartment.save
        format.html  { redirect_to(@apartment,
                                   :notice => 'Post was successfully created.') }
        format.json  { render :json => @apartment,
                              :status => :created, :location => @apartment }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @apartment.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for (@apartment) do |f| %>
    <% if @apartment.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @apartment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :loan %>
      <%= f.select :loan, [['ano', true], ['nie', false]]%>
    </div>

    <div class="field">
      <%= f.label :ownership %>
      <%= f.select :ownership, [['osobne', 1]]%>
    </div>

    <div class="field">
      <%= f.label :prize %>
      <%= f.text_field :prize %>
    </div>

    <div class="field">
      <%= f.label :age %>
      <%= f.text_field :age %>
    </div>

    <div class="field">
      <%= f.label :area %>
      <%= f.text_field :area %>
    </div>

    <div class="field">
      <%= f.label :bathroom %>
      <%= f.select :bathroom, [['1', 1],['2', 2],['3', 3],['4', 4],['5', 5]] %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/apartments/_form.html.haml
= form_for @apartment do |f|
  - if @apartment.errors.any?
    #errorExplanation
      %h2= pluralize(@apartment.errors.count, "error")
      %ul
        - @apartment.errors.full_messages.each do |msg|
          %li= msg

  .field
    =f.label :description
    =f.text_field :description

  .field
    =f.label :name
    =f.text_field :name

  .field
    = f.label :loan
    = f.select :loan, [['ano', true], ['nie', false]]

  .field
    = f.label :ownership
    = f.select :ownership, [['osobne', 1]]


  .field
    = f.label :prize
    = f.text_field :prize


  .field
    = f.label :age
    = f.text_field :age


  .field
    = f.label :area
    = f.text_field :area


  .field
    = f.label :bathroom
    = f.select :bathroom, [['1', 1],['2', 2],['3', 3],['4', 4],['5', 5]]


  %p.button
    = f.submit

app/views/apartments/index.html.erb
Property index
<hr>
<% @apartment.each do |apartment|  %>
    Name: <%= apartment.name %>
    <%= link_to 'Show', apartment %>  <br>
<% end %>



<% if can? :add, Apartment %>
    <hr>
    <%= link_to 'New apartments', new_apartment_path %>
<% end %>

app/views/apartments/index.html.haml
%hr
-@apartment.each do |apartment|
    Name:
    = apartment.name
    = link_to 'Show', apartment
    %br

-if can? :add, Apartment
    %hr
    = link_to 'New apartments', new_apartment_path

app/views/apartments/new.html.erb
<h1>New apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/new.html.haml
%h1= 'New apartment'

= render 'form'
= link_to 'Back', apartments_path

app/views/apartments/show.html.erb
Property show
<hr>

Name: <%= @apartment.name %>  <br>

Desc: <%= @apartment.description %>  <br>

Prize: <%= @apartment.prize %>  <br>

Loan: <%= @apartment.loan %>  <br>

Ownership: <%= @apartment.ownership %>  <br>

app/views/apartments/show.html.haml
%p= 'Property show'
%hr

=@apartment.name
%br
=@apartment.description
%br
=@apartment.prize
%br
=@apartment.loan
%br
=@apartment.ownership