config/routes.rb
Web::Application.routes.draw do

  devise_for :users

  resources :apartments
  resources :houses
  resources :filters

  root :to => "filters#index"

end

app/views/layouts/_content.html.erb
<div class="page-header">
  <%= yield %>
</div>

app/views/layouts/_content.html.haml
.page-header
    = yield

app/views/layouts/_header.html.erb
<div class="row">

  <div class="span6">
    <div class="bsa well">

    </div>
  </div>
</div>

<div class="subnav">
  <ul class="nav nav-pills">
    <div id="user_nav">
      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or
          <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div>
  </ul>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_header.html.haml
.row
    .span6
    .bsa.well

.subnav
%ul.nav.nav-pills
    #user_nav
    -if user_signed_in?
        ='Signed in as'
        =current_user.email
        =link_to 'Sing out', destroy_user_session_path, :method => :delete
    -else
        = link_to "Sign in", new_user_session_path
        = link_to "Sign up", new_user_registration_path


%p.notice= notice
%p.alert= alert

app/views/layouts/_menu.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<%= link_to "RealEstatePortal", filters_path, :class => "brand"%>
<div class="nav-collapse collapse" id="main-menu">
  <ul class="nav" id="main-menu-left">
    <li><%= link_to "Apartment", apartments_path %></li>
    <li><%= link_to "House", houses_path %></li>
  </ul>
</div>

app/views/layouts/_menu.html.haml
= link_to "RealEstatePortal", filters_path, :class => "brand"
.nav-collapse.collapse#main-menu
    %ul.nav#main-menu-left
        %li=link_to "Apartment", apartments_path
        %li= link_to "House", houses_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealEstatePortal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="preview" id="top" data-spy="scroll" data-target=".subnav" data-offset="80">

<!-- Navbar ================================================== -->
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= render :partial => "layouts/menu" %>
    </div>
  </div>
</div>

<div class="container">
  <header class="jumbotron subhead" id="overview">
    <%= render :partial => "layouts/header" %>
  </header>


  <section id="typography">
    <%= render :partial => "layouts/content" %>
  </section>




</div>



</body>
</html>

app/views/layouts/application.html.haml
%html
  %head
    %title RealEstatePortal
    = stylesheet_link_tag "application", :media => "all"
    =  stylesheet_link_tag "application", :media => "all"
    =  stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags

%body.preview#top
	
  .navbar.navbar-fixed-top#top
    .navbar-inner
      .container
        = render :partial => "layouts/menu"

    .container
      %header{:class => "jumbotron subhead", :id => "overview"}
      = render :partial => "layouts/header"

    %section#typography
      = render :partial => "layouts/content"